spring:
  datasource:
    one:
      username: root
      password: root
      jdbc-url: jdbc:mariadb://localhost:3306/myschool
      driver-class-name: org.mariadb.jdbc.Driver
    two:
      username: root
      password: root
      url: jdbc:mariadb://localhost:3306/myschool
      driver-class-name: org.mariadb.jdbc.Driver




mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: org.example.domain

